### ISSUE TITLE
list items having bare CDATA content

### ISSUE THREAD

**Issue by Alex-Jordan** [PCCMathSAC/apex-mbx#11]
The DTD requires an `<li>` to have proper children from among `p|md|mdn|ul|ol|dl`, not raw CDATA. So for instance 
`<li><p>This is a sentence.</p></li>`
not
`<li>This is a sentence.</li>`

As an example, line 66 from https://github.com/APEXCalculus/APEXCalculus_Source/blob/master/text/01_Limit_Introduction.tex is an `\item` that gets turned into an `<li>` with CDATA content. Is there a clever way to detece if it's OK to insert `<p>`s in places like this? I'd rather they all get `<p>`s and then manually change some to other things as we manually edit than manually make most of them have the `<p>`.

**Comment by davidfarmer** [comment]
I have recently iminemented "line" instead of "br", and I think
that broke having "p" in "li".

Fixed in next pull request.

Do I need "p" around the content of this li?  I'll assume
'yes' for now.

<li><line>some words</line>
<line>more words</line>
</li>

**Comment by Alex-Jordan** [comment]
> Do I need "p" around the content of this li? I'll assume
> 'yes' for now.
> 
> <li><line>some words</line>
> <line>more words</line>
> </li>

I don't think that Rob has implemented <line> this way yet. I would assume
that eventually if it becomes implemented within an <li>, that a <p> would
not wrap around the <line>s. But I also think putting a <p> there now would
be helpful for the manual conversion. We'll look at the original intent for
the line break and see if there's an approved way to achieve the same
effect, and likely need the <p>.

> On Thu, 7 Jul 2016, Alex Jordan wrote:
> 
> > The DTD requires an <li> to have proper children from among
> > p|md|mdn|ul|ol|dl, not raw CDATA. So for
> > instance
> > <li><p>This is a sentence.</p></li>
> > not
> > <li>This is a sentence.</li>
> > 
> > As an example, line 66 from
> > 
> > https://github.com/APEXCalculus/APEXCalculus_Source/blob/master/text/01_Limit_Introduction.tex
> > is an
> > \item that gets turned into an <li> with CDATA content. Is there a
> > clever way to detece if it's OK to
> > insert <p>s in places like this? I'd rather they all get <p>s and then
> > manually change some to other
> > things as we manually edit than manually make most of them have the <p>.
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub, or mute the
> > thread.[AAM6LHGOsPwwqPYCiNiRb-iGre3WActzks5qTeTngaJpZM4JHvbZ.gif]
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/PCCMathSAC/apex-mbx/issues/11#issuecomment-231338526,
> or mute the thread
> https://github.com/notifications/unsubscribe/AEg3ACTzeUcOuahnd9bwvXkICXg6_EIfks5qTjYugaJpZM4JHvbZ
> .

## 

Alex Jordan
Mathematics Instructor
Portland Community College

**Comment by Alex-Jordan** [comment]
Addressed by #13.
