### ISSUE TITLE
Answer blanks

### ISSUE THREAD

**Issue by Alex-Jordan** [PCCMathSAC/apex-mbx#12]
In https://github.com/APEXCalculus/APEXCalculus_Source/blob/master/exercises/01_01_ex_20.tex, there is `\underline{\hskip 15pt}`, intended to be an answer blank. Now that MBX has 
`<fillin characters="1.5">`
that would be better. Right now SL2X ignored it completely. Of course it is not clear that every place an author puts such a thing is intended to be a fill-in-the-blank. But maybe.

Only mentioning this one in case it is generally helpful for improving SL2X. It will be irrelevant to us since we will make the exercise a WeBWorK exercise.

**Comment by davidfarmer** [comment]
I have changed all the \underline{\hskip *} to <fillin />.

We'll see if it needs to be dynamic based on the amount of hskip
(which, unfortunately, uses more that one set of units).

Note that there will be fillin in math mode, so we need to decide
how to handle that.

**Comment by Alex-Jordan** [comment]
Addressed by #13.
